# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_groups', '0002_auto_20161217_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='committee',
            old_name='description_long',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='interestgroup',
            old_name='description_long',
            new_name='text',
        ),
    ]
