# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 22:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0013_merge_20171015_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousStudentContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('deleted', models.BooleanField(db_index=True, default=False, editable=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.RemoveField(
            model_name='company',
            name='previous_contacts',
        ),
        migrations.AddField(
            model_name='previousstudentcontact',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_student_contacts', to='companies.Company'),
        ),
        migrations.AddField(
            model_name='previousstudentcontact',
            name='created_by',
            field=models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previousstudentcontact_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='previousstudentcontact',
            name='updated_by',
            field=models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previousstudentcontact_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='previousstudentcontact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_student_contacts', to=settings.AUTH_USER_MODEL),
        ),
    ]
