# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 23:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_auto_20171102_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previousstudentcontact',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
