# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_auto_20171102_2313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='previousstudentcontact',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='previousstudentcontact',
            name='end',
        ),
        migrations.RemoveField(
            model_name='previousstudentcontact',
            name='start',
        ),
        migrations.AddField(
            model_name='previousstudentcontact',
            name='current',
            field=models.BooleanField(default=False),
        ),
    ]
