# Generated by Django 2.0.2 on 2018-02-26 17:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20180223_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='possible_pools',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
        ),
    ]
