# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170903_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='abakus_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='users.AbakusGroup'),
        ),
    ]
